import Foundation
import UIKit

enum ReportExporter {
    static func plainText(from result: AnalysisResult) -> String {
        var lines: [String] = []
        lines.append("CoParse Report")
        lines.append(String(repeating: "=", count: 40))
        lines.append("Title: \(result.title)")
        lines.append("Date: \(result.createdAt.formatted(date: .abbreviated, time: .shortened))")
        lines.append("Type: \(result.contractType.replacingOccurrences(of: "_", with: " "))")
        lines.append("Role: \(result.role)")
        lines.append("Score: \(result.overallScore)/100")
        lines.append("Readiness: \(result.signatureReadiness.recommendationText)")
        if let conf = result.analysisConfidence {
            lines.append("Confidence: \(conf.level) — \(conf.summary)")
        }
        if let ocr = result.ocrConfidence {
            lines.append("OCR quality: \(Int(ocr * 100))%")
        }
        lines.append("")
        lines.append("DISCLAIMER")
        lines.append("Educational information only — not legal advice. Verify against the original document.")
        lines.append("")
        lines.append("CATEGORY SCORES")
        for (key, value) in result.categoryScores.sorted(by: { $0.key < $1.key }) {
            lines.append("- \(key.replacingOccurrences(of: "_", with: " ")): \(value)/100")
        }
        lines.append("")
        lines.append("TOP ISSUES")
        if result.topIssues.isEmpty {
            lines.append("- None flagged high/medium")
        } else {
            for issue in result.topIssues {
                lines.append("- [\(issue.riskLevel.uppercased())] \(issue.theme): \(issue.plainEnglish)")
            }
        }
        lines.append("")
        lines.append("MISSING PROTECTIONS")
        if result.missingProtections.isEmpty {
            lines.append("- None flagged by template checks")
        } else {
            for m in result.missingProtections {
                lines.append("- \(m.label): \(m.detail)")
            }
        }
        lines.append("")
        lines.append("QUESTIONS TO ASK")
        for q in result.questionsToAsk {
            lines.append("- (\(q.context)) \(q.question)")
        }
        if let next = result.nextSteps {
            if !next.ifThenNudges.isEmpty {
                lines.append("")
                lines.append("IF / THEN")
                for nudge in next.ifThenNudges {
                    lines.append("- If \(nudge.ifCondition) → \(nudge.thenAction)")
                }
            }
            if let email = next.emailTemplates.first {
                lines.append("")
                lines.append("EMAIL TEMPLATE")
                lines.append("Subject: \(email.subject)")
                lines.append(email.body)
            }
        }
        lines.append("")
        lines.append("Generated by CoParse · On-device analysis · Free")
        return lines.joined(separator: "\n")
    }

    static func shareItems(from result: AnalysisResult) -> [Any] {
        let text = plainText(from: result)
        let safeTitle = result.title
            .replacingOccurrences(of: "/", with: "-")
            .replacingOccurrences(of: ":", with: "-")
        let filename = "CoParse-\(safeTitle).txt"
        let url = FileManager.default.temporaryDirectory.appendingPathComponent(filename)
        try? text.write(to: url, atomically: true, encoding: .utf8)
        return [url, text]
    }
}

struct ShareSheet: UIViewControllerRepresentable {
    var items: [Any]

    func makeUIViewController(context: Context) -> UIActivityViewController {
        UIActivityViewController(activityItems: items, applicationActivities: nil)
    }

    func updateUIViewController(_ uiViewController: UIActivityViewController, context: Context) {}
}
